#ifndef DPRINTF_H
#define DPRINTF_H
#include <stdarg.h>
enum {
  PRINT_INCOMPLETE, PRINT_MALFORMED,
  PRINT_PERCENT, PRINT_CHAR,
  PRINT_STRING, PRINT_INT,
  PRINT_UINT, PRINT_BINARY,
  PRINT_OCTAL, PRINT_HEX,
  PRINT_DOUBLE, PRINT_EXPONENT,
  PRINT_GENERAL, PRINT_HEXPONENT,
  PRINT_POINTER, PRINT_TELL,
  PRINT_ERROR, SCAN_SET,

  SCAN_INCOMPLETE = PRINT_INCOMPLETE, SCAN_MALFORMED = PRINT_MALFORMED,
  SCAN_PERCENT = PRINT_PERCENT, SCAN_CHAR = PRINT_CHAR,
  SCAN_STRING = PRINT_STRING, SCAN_INT = PRINT_INT,
  SCAN_UINT = PRINT_UINT, SCAN_BINARY = PRINT_BINARY,
  SCAN_OCTAL = PRINT_OCTAL, SCAN_HEX = PRINT_HEX,
  SCAN_DOUBLE = PRINT_DOUBLE, SCAN_EXPONENT = PRINT_EXPONENT,
  SCAN_GENERAL = PRINT_GENERAL, SCAN_HEXPONENT = PRINT_HEXPONENT,
  SCAN_POINTER = PRINT_POINTER, SCAN_TELL = PRINT_TELL,
};
enum {
  PRINT_ALLCAPS = 1,
  PRINT_LEFT_JUSTIFY = 2,
  PRINT_SIGN = 4,
  PRINT_SPACE = 8,
  PRINT_ALTER = 16,
  PRINT_ZERO_EXTEND = 32,
  PRINT_ROUNDTRIP = 64,
  SCAN_IGNORE = 128,
};

enum {
  PRINT_SHORTSHORT,
  PRINT_SHORT,
  PRINT_WORD,
  PRINT_LONG,
  PRINT_LONGLONG,
  PRINT_SIZE,
  PRINT_MAX,
  PRINT_PTRDIFF,
  PRINT_EXACT,
  PRINT_FAST,

  SCAN_SHORTSHORT = PRINT_SHORTSHORT,
  SCAN_SHORT = PRINT_SHORT,
  SCAN_WORD = PRINT_WORD,
  SCAN_LONG = PRINT_LONG,
  SCAN_LONGLONG = PRINT_LONGLONG,
  SCAN_SIZE = PRINT_SIZE,
  SCAN_MAX = PRINT_MAX,
  SCAN_PTRDIFF = PRINT_PTRDIFF,
  SCAN_EXACT = PRINT_EXACT,
  SCAN_FAST = PRINT_FAST,
};

typedef struct print_specifier {
  int print_kind;
  int kind_width;
  int kind_exact_width;
  int flags;
  int field_width;
  int precision;
  int chars_consumed;
} print_specifier;

#endif
